### ISSUE TITLE
Support Rails 4.2 and Rails 5 at the same time

### ISSUE THREAD

**Issue by connorshea** [mirego/activerecord_sane_schema_dumper#6]
In order to make the upgrade to Rails 5 as smooth as possible it'd be nice if this gem could support both for at least one version. This way, we can upgrade the gem in a separate PR/MR from the Rails 5 upgrade.

I can help do this if there's interest.

**Comment by remiprev** [comment]
Thanks, but this already has been discussed. The gem code is really simple and there was no new feature between `0.2` (Rails 4) and `1.0` (Rails 5).

Since the gem will become [100% obsolete with Rails 5.1](https://github.com/rails/rails/pull/25675), I think 1.0 will be the last version we release 😄
